### ISSUE TITLE
Add scala.js support

### ISSUE THREAD

**Issue by ngbinh** [jvican/dijon#176]
Is `dijon` scala.js friendly? I can work on it but not sure if it is something possible.

**Comment by pathikrit** [comment]
It should be doable. It is just basic scala without dependencies

**Comment by jvican** [comment]
@ngbinh I can review and merge Scala.js support if you make a PR for it.

**Comment by ngbinh** [comment]
@jvican great, will find some time to make a PR for that soon

**Comment by plokhotnyuk** [comment]
Fixed by https://github.com/jvican/dijon/pull/199

Please peek v0.5.0 release
