### ISSUE TITLE
Release of Dijon v0.4.0 wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [jvican/dijon#63]
@pathikrit Hi, Pathikrit!

The latest version of jsoniter-scala breaks backward binary compatibility.
It was done for easier evolving when adding new configuration flags or new routines to support more types/representations for versions 1.x until 2.0.0.

Please release the Dijon v0.4.0 with all merged changes.

Thanks,
Andriy.

**Comment by plokhotnyuk** [comment]
@pathikrit Pathikrit, please, cute a release!

Scala 3 is coming and some refactoring that could break backward binary compatibility can be required!

**Comment by pathikrit** [comment]
Hi @plokhotnyuk - I have completely lost touch with this repo. I would be happy to give you over the keys so you can take over the release process? Let's chat in private in gitter.im or email me? Thanks!

**Comment by plokhotnyuk** [comment]
I've sent a message to your email from the GitHub account profile.

**Comment by jvican** [comment]
I'm getting the following exception with the current 0.3.0: `java.lang.NoSuchMethodError: com.github.plokhotnyuk.jsoniter_scala.core.WriterConfig$.apply$default$1()Z`.
  
I'm happy to help making releases here as well, I'm interested in a new release that it's compatible with the latest jsoniter-scala artifact.

**Comment by plokhotnyuk** [comment]
The Dijon is a small library, so as a workaround for some use cases it could be an option to inject it as an external sub-project:
```
lazy val dijon = ProjectRef(uri("https://github.com/pathikrit/dijon.git#master"), "dijon")
lazy val root = (project in file(".")).dependsOn(dijon)
```

**Comment by gabrieljones** [comment]
I really want to use this. For reasons I am using gradle and not sbt(internal Nexus Layout is Strict not Permissive). So the workaround is not available to me.

**Comment by htmldoug** [comment]
I'm interested as well. @pathikrit were you able to connect with @plokhotnyuk about the future of this repo? What's the best path forward?

**Comment by plokhotnyuk** [comment]
@jvican @gabrieljones @htmldoug As a workaround I've cut 0.4.0 released under `com.github.plokhotnyuk` organization: https://github.com/plokhotnyuk/dijon/releases/tag/v0.4.0

@pathikrit I would prefer to develop and release under your organization. Please email me if you consider setting up Travis CI releases or propose other options for safe and regular releasing.

**Comment by jvican** [comment]
Thanks for that. I'm also not using sbt.
  
I can volunteer to help maintaining the project if need be @pathikrit

**Comment by pathikrit** [comment]
I am happy to transfer ownership of this to someone else - please DM me on gitter and we can work through that.

**Comment by jvican** [comment]
I've contacted you privately in Gitter.

**Comment by pathikrit** [comment]
I just started transfer to @jvican :

![image](https://user-images.githubusercontent.com/899219/96752654-c2dcac80-139c-11eb-9500-ae90cd2ee30a.png)

**Comment by jvican** [comment]
Thanks @pathikrit, I'll cut a release within the next two days.

**Comment by jvican** [comment]
Hi folks, I finally got around to publishing 0.4.0 and adding support for GitHub Actions. The release is on its way to Maven Central. I had to change the coordinates to publish, so the new coordinates are 'me.vican.jorge' and I've changed the package from `com.pathikrit.bhowmick.dijon` to `dijon` only for brevity. The README already has these changes documented.
